const defaultTheme = {
  colorBlack: '#333',
  colorWhite: '#fff',
  colorBlueBackground: '#D8ECFE',
  colorGreenBackground: '#E1EDCE',
  colorDarkBlue: '#C4E2FF',
  colorCard: '#E1EDCE',
  colorBadgeCard: '#88AA4D',
  colorCardNegative: '#F8DDD7',
  colorBadgeCardNegative: '#F75531',
  colorButton: '#FC9B27',
  colorHoverArFocusButton: '#FC7427',
  backgroundColorGray: '#f7f7f7',
  pagePadding: '90px',
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: '18px',
  pageWidth: '1280px',
  fontWeightDefault: '400',
  lineHeightDefault: '150%',
  headerWidth: '80px',
  footerWidth: '80px',
  indent: '20px',
};

export default defaultTheme;
